feat(s3-proxy): Add `envFrom` to allow multiple ConfigMaps to be passed as environment variables
oxyno-zeta/helm-charts-v2 pull request #10
Opened 2022-06-22 17:32 UTC by EternalDeiwos

The title pretty much describes what this does. Currently the values only allows us to manually specify env values, or pass one existing secret to be mounted into the secrets directory. Ideally we'd be able to mount multiple secrets but this is a decent workaround until something like that exists.

This handles providing both Secrets and ConfigMaps as environment variables which could then be specified for whatever purpose via the config.

Details on `envFrom` can be found [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables)

This should not introduce any breaking changes.

2022-06-23 06:02 UTC, oxyno-zeta requested changes
Hello @EternalDeiwos !

Thanks for your contribution ! That's really cool !
For the MR in itself: I never used this before but this seems to be a good thing. I will be happy to merge it when you have patched following the comment on the code.

Have a good day!

Oxyno-zeta

2022-06-23 06:02 UTC, oxyno-zeta commented on charts/s3-proxy/templates/deployment.yaml
> +          envFrom: {{- toYaml .Values.livenessProbe | nindent 10 }}
Should be ".Values.envFrom" and I think the indent have to be changed but cannot be sure on phone

2022-06-23 06:06 UTC, EternalDeiwos commented on charts/s3-proxy/templates/deployment.yaml
> +          envFrom: {{- toYaml .Values.livenessProbe | nindent 10 }}
🤦‍♂️ Fixing.

2022-06-24 10:13 UTC, EternalDeiwos commented
@oxyno-zeta I've made the requested changes. Good catch. Any chance you could do a patch release after you've merged this?

2022-06-24 10:16 UTC, oxyno-zeta commented
Hello @EternalDeiwos ,

Yes ! The CI will publish automatically the new version. But for this, you have to change the version in the Chart.yaml. New version must be `2.12.0` [here](https://github.com/oxyno-zeta/helm-charts-v2/blob/master/charts/s3-proxy/Chart.yaml#L21) .

Can you edit your MR for that ?

Thanks !

2022-06-24 10:17 UTC, oxyno-zeta commented on charts/s3-proxy/templates/deployment.yaml
> +          envFrom: {{- toYaml .Values.livenessProbe | nindent 10 }}
No problem :)

2022-06-24 10:22 UTC, EternalDeiwos commented
@oxyno-zeta Done

2022-06-24 10:23 UTC, oxyno-zeta approved these changes

2022-06-24 10:24 UTC, merged

2022-06-24 10:25 UTC, oxyno-zeta commented
@EternalDeiwos : s3-proxy 2.12.0 chart is released ! Thanks for your contribution !

2022-06-24 10:25 UTC, oxyno-zeta commented
Hope you are enjoying the app ;)

2022-06-24 10:26 UTC, EternalDeiwos commented
It is certainly useful; thank you for making it.